# Translations template for PROJECT.
# Copyright (C) 2024 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2024.
#
msgid ""
msgstr ""
"Project-Id-Version: PROJECT VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2024-07-16 11:13+0200\n"
"PO-Revision-Date: 2025-02-27 12:32+0000\n"
"Last-Translator: PanierAvide <adrien@pavie.info>\n"
"Language-Team: Spanish <http://weblate.panoramax.xyz/projects/panoramax/api/"
"es/>\n"
"Language: es\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"
"X-Generator: Weblate 5.4.3\n"
"Generated-By: Babel 2.15.0\n"

#: geovisio/templates/main.html:45
msgid "Simple 360° geolocated pictures hosting"
msgstr "Alojamiento sencillo para imágenes 360° geolocalizadas"

#: geovisio/templates/main.html:47
msgid "Full page version"
msgstr "Versión de página completa"

#: geovisio/templates/main.html:51
msgid "Viewer"
msgstr "Visor"

#: geovisio/templates/main.html:52
msgid "Embed pre-configured viewer"
msgstr "Incrustar visor pre-configurado"

#: geovisio/templates/main.html:53
msgid "Easiest way to have a working GeoVisio viewer on your website"
msgstr "La forma más fácil de incluir un visor GeoVisio en tu página web"

#: geovisio/templates/main.html:59
msgid "Use JS library"
msgstr "Usar biblioteca JS"

#: geovisio/templates/main.html:60
msgid "A completely configurable viewer for your website"
msgstr "Un visor completamente configurable para tu página web"

#: geovisio/templates/main.html:82
msgid "Links"
msgstr "Enlaces"

#: geovisio/templates/main.html:84
msgid "Pictures viewer"
msgstr "Visor de imágenes"

#: geovisio/templates/main.html:86
msgid "API docs"
msgstr "Documentación de la API"

#: geovisio/templates/main.html:88
msgid "JS library docs"
msgstr "Documentación de la biblioteca JS"

#: geovisio/templates/main.html:90
msgid "Repositories"
msgstr "Repositorios"

#: geovisio/templates/viewer.html:22
msgid "You need to enable JavaScript to run this app."
msgstr "Debes activar JavaScript para poder ver esta aplicación."

#: geovisio/utils/auth.py:164
msgid "Authentication is mandatory"
msgstr "Es obligatorio autenticarse"

#: geovisio/utils/auth.py:292
msgid "Only Bearer token are supported"
msgstr "Sólo se admite token Bearer"

#: geovisio/utils/pictures.py:305
#, python-format
msgid ""
"Invalid '%(format)s' format for image, only the following formats are "
"available: %(allowed_formats)s"
msgstr ""
"Formato '%(format)s' inválido para la imagen, solo están disponibles los "
"siguientes formatos: %(allowed_formats)s"

#: geovisio/utils/pictures.py:421
msgid "Picture can't be found, you may check its ID"
msgstr "No se encuentra la imagen, puedes comprobar su ID"

#: geovisio/utils/pictures.py:424
msgid "Picture is not available (either hidden by admin or processing)"
msgstr ""
"La imagen no está disponible (ocultada por un administrador, o todavía está "
"procesándose)"

#: geovisio/utils/pictures.py:432
msgid "HD Picture file is not available"
msgstr "El fichero imagen de alta calidad no está disponible"

#: geovisio/utils/pictures.py:451
msgid "Picture derivates file are not available"
msgstr "Ficheros de imágenes derivadas no disponibles"

#: geovisio/utils/pictures.py:468 geovisio/web/pictures.py:59
#: geovisio/web/pictures.py:108 geovisio/web/pictures.py:226
msgid "Unable to read picture on filesystem"
msgstr "Imposible leer el fichero desde el sistema de ficheros"

#: geovisio/utils/sequences.py:372
msgid ""
"Sort by file date is not possible on this sequence (no file date "
"information available on pictures)"
msgstr ""
"No se puede ordenar por fecha de fichero en esta secuencia (las imágenes no "
"tienen información de fecha)"

#: geovisio/utils/sequences.py:391
#, python-format
msgid ""
"Sort using %(sort)s is not possible on this sequence, picture %(pic)s is "
"missing mandatory metadata"
msgstr ""
"No se puede ordenar por %(sort)s en esta secuencia, la imagen %(pic)s no "
"contiene los metadatos necesarios"

#: geovisio/utils/tokens.py:43
msgid "JWT token signature does not match"
msgstr "La firma del JWT no coincide"

#: geovisio/utils/tokens.py:59
msgid "Token does not exist anymore"
msgstr "El token ya no existe"

#: geovisio/utils/tokens.py:63
msgid ""
"Token not yet claimed, this token cannot be used yet. Either claim this "
"token or generate a new one"
msgstr ""
"El token no ha sido reclamado aún, no puede utilizarse. Reclama el token, o "
"bien genera uno nuevo"

#: geovisio/utils/upload_set.py:143 geovisio/web/params.py:359
msgid "Unsupported filter parameter"
msgstr "Parámetro de filtro no admitido"

#: geovisio/web/auth.py:62
msgid "Impossible to finish authentication flow"
msgstr "No se pudo completar el proceso de autenticación"

#: geovisio/web/auth.py:66
msgid ""
"You can try to clear your cookies and retry. If the problem persists, "
"contact your instance administrator."
msgstr ""
"Puedes probar a borrar las cookies y reintentar. Si el problema persiste, "
"ponte en contacto con el administrador de la instancia."

#: geovisio/web/collections.py:263
#, python-format
msgid "There is no collection created after %(d)s"
msgstr "No hay colecciones creadas después del %(d)s"

#: geovisio/web/collections.py:265
#, python-format
msgid "There is no collection created before %(d)s"
msgstr "No hay colecciones creadas antes del %(d)s"

#: geovisio/web/collections.py:372 geovisio/web/items.py:372
msgid "Collection doesn't exist"
msgstr "La colección no existe"

#: geovisio/web/collections.py:431
msgid "Impossible to find a thumbnail for the collection"
msgstr "No se encuentra vista previa de la colección"

#: geovisio/web/collections.py:544 geovisio/web/items.py:1142
msgid ""
"Picture visibility parameter (visible) should be either unset, true or "
"false"
msgstr ""
"El parámetro de visibilidad de la imagen (visible) debe ser true, false, o "
"no definirse"

#: geovisio/web/collections.py:550
msgid ""
"Sequence title is not valid, should be a string with a max of 250 "
"characters"
msgstr ""
"El título de la secuencia no es válido, debería ser una cadena de 250 "
"caracteres como máximo"

#: geovisio/web/collections.py:556
msgid "Sort order parameter is invalid"
msgstr "El parámetro de ordenación no es válido"

#: geovisio/web/collections.py:567
msgid ""
"Relative heading is not valid, should be an integer in degrees from -180 "
"to 180"
msgstr ""
"La orientación relativa no es válida, debería ser un número entero en grados "
"entre -180 y 180"

#: geovisio/web/collections.py:584
#, python-format
msgid "Sequence %(c)s wasn't found in database"
msgstr ""

#: geovisio/web/collections.py:588
msgid "You're not authorized to edit this sequence"
msgstr "No tienes autorización para modificar esta secuencia"

#: geovisio/web/collections.py:597
#, python-format
msgid "Sequence %(c)s is in %(s)s state, its visibility can't be changed for now"
msgstr ""
"La secuencia %(c)s está en estado %(s)s, su visibilidad no puede modificarse "
"por el momento"

#: geovisio/web/collections.py:696
#, python-format
msgid "Collection %(c)s wasn't found in database"
msgstr "La colección %(c)s no se encontró en la base de datos"

#: geovisio/web/collections.py:793
#, fuzzy
msgid "Sequence doesn't exists"
msgstr "La secuencia no existe"

#: geovisio/web/collections.py:938 geovisio/web/stac.py:340
#, python-format
msgid "Impossible to find user %(u)s"
msgstr "No se encuentra el usuario %(u)s"

#: geovisio/web/collections.py:969 geovisio/web/stac.py:350
#, python-format
msgid "No data loaded for user %(u)s"
msgstr "No se pudieron cargar datos del usuario %(u)s"

#: geovisio/web/collections.py:971
msgid "No matching sequences found"
msgstr "No se encuentran secuencias correspondientes"

#: geovisio/web/items.py:335
msgid "limit parameter should be an integer between 1 and 10000"
msgstr "el parámetro de límite debe ser un número entero entre 1 y 10000"

#: geovisio/web/items.py:337
msgid "limit parameter should be a valid, positive integer (between 1 and 10000)"
msgstr ""
"el parámetro debe ser un número entero, positivo y válido (entre 1 y 10000)"

#: geovisio/web/items.py:342
msgid "`startAfterRank` and `withPicture` are mutually exclusive parameters"
msgstr "`startAfterRank` y `withPicture` son mutuamente excluyentes"

#: geovisio/web/items.py:349
msgid "startAfterRank parameter should be a positive integer (starting from 1)"
msgstr "El parámetro startAfterRank debe ser un número entero (empezando por 1)"

#: geovisio/web/items.py:351
msgid "startAfterRank parameter should be a valid, positive integer"
msgstr "El parámetro startAfterRank debe ser un número entero positivo"

#: geovisio/web/items.py:378
#, python-format
msgid "No more items in this collection (last available rank is %(r)s)"
msgstr "No hay más elementos en esta colección (el último índice es %(r)s)"

#: geovisio/web/items.py:388
#, fuzzy, python-format
msgid "Picture with id %(p)s does not exist"
msgstr "La imagen con id %(p)s no existe"

#: geovisio/web/items.py:674
msgid "Item doesn't exist"
msgstr "El elemento no existe"

#: geovisio/web/items.py:733
msgid "Search using POST method should have a JSON body"
msgstr "La búsqueda con método POST debe incluir un cuerpo en formato JSON"

#: geovisio/web/items.py:742
msgid "Parameter limit must be either empty or a number between 1 and 10000"
msgstr ""
"El parámetro limit debe estar vacío, o bien ser un número entero entre 1 y "
"10000"

#: geovisio/web/items.py:798
msgid ""
"Parameter place_fov_tolerance must be either empty or a number between 2 "
"and 180"
msgstr ""
"El parámetro place_fov_tolerance debe estar vacío o ser un número entre 2 y "
"180"

#: geovisio/web/items.py:820
msgid ""
"Parameter intersects should contain a valid GeoJSON Geometry (not a "
"Feature)"
msgstr ""
"El parámetro intersects debe contener una entrada Geometry GeoJSON válida ("
"no una Feature)"

#: geovisio/web/items.py:836
msgid "Parameter ids should be a JSON array of strings"
msgstr "El parámetro ids debe ser una lista JSON de cadenas"

#: geovisio/web/items.py:848
msgid "Parameter collections should be a JSON array of strings"
msgstr "El parámetro collections debe ser una lista JSON de cadenas"

#: geovisio/web/items.py:859
msgid "Picture doesn't exist"
msgstr "La imagen no existe"

#: geovisio/web/items.py:962 geovisio/web/upload_set.py:447
msgid "Content type should be multipart/form-data"
msgstr "El Content-Type debe ser multipart/form-data"

#: geovisio/web/items.py:966
msgid "Missing \"position\" parameter"
msgstr "Falta el parámetro \"position\""

#: geovisio/web/items.py:973
msgid "Position in sequence should be a positive integer"
msgstr "La posición en secuencia debe ser un número entero positivo"

#: geovisio/web/items.py:987 geovisio/web/upload_set.py:340
msgid ""
"Longitude cannot be overridden alone, override_latitude also needs to be "
"set"
msgstr ""
"La longitud no se puede forzar sola, hay que forzar la latitud también con "
"override_latitude"

#: geovisio/web/items.py:989 geovisio/web/upload_set.py:342
msgid ""
"Latitude cannot be overridden alone, override_longitude also needs to be "
"set"
msgstr ""
"La latitud no se puede forzar sola, hay que forzar la longitud también con "
"override_longitude"

#: geovisio/web/items.py:990 geovisio/web/upload_set.py:315
#, python-format
msgid "For parameter `override_longitude`, `%(v)s` is not a valid longitude"
msgstr ""
"Para el parámetro `override_longitude`, `%(v)s` no es una longitud válida"

#: geovisio/web/items.py:991 geovisio/web/upload_set.py:320
#, python-format
msgid "For parameter `override_latitude`, `%(v)s` is not a valid latitude"
msgstr "Para el parámetro `override_latitude`, `%(v)s` no es una latitud válida"

#: geovisio/web/items.py:1010
msgid "Picture blur status should be either unset, true or false"
msgstr ""
"El estado de difuminado de la imagen debe ser true, false, o no estar "
"definido"

#: geovisio/web/items.py:1014
msgid "No picture file was sent"
msgstr "No se envió ningún fichero de imagen"

#: geovisio/web/items.py:1020 geovisio/web/upload_set.py:365
msgid "Picture file is either missing or in an unsupported format (should be jpg)"
msgstr ""
"El fichero de imagen falta o está en un formato no admitido (debe ser jpg)"

#: geovisio/web/items.py:1027
#, python-format
msgid "Sequence %(s)s wasn't found in database"
msgstr ""

#: geovisio/web/items.py:1061
msgid "Picture at given position already exist"
msgstr "Ya existe una imagen en la posición dada"

#: geovisio/web/items.py:1063 geovisio/web/upload_set.py:521
msgid "Impossible to parse picture metadata"
msgstr "No se pueden leer los metadatos de la imagen"

#: geovisio/web/items.py:1071 geovisio/web/upload_set.py:529
msgid "Picture wasn't correctly saved in filesystem"
msgstr "La imagen no se guardó correctamente en el sistema de ficheros"

#: geovisio/web/items.py:1154
msgid ""
"Heading is not valid, should be an integer in degrees from 0° to 360°. "
"North is 0°, East = 90°, South = 180° and West = 270°."
msgstr ""
"La orientación no es válida, debería ser un número entero en grados, de 0° "
"to 360°. El norte es 0°, este = 90°, sur = 180° y oeste = 270°."

#: geovisio/web/items.py:1171 geovisio/web/items.py:1262
#, python-format
msgid "Picture %(p)s wasn't found in database"
msgstr "La imagen %(p)s no se encuentra en la base de datos"

#: geovisio/web/items.py:1175 geovisio/web/items.py:1266
msgid "You're not authorized to edit this picture"
msgstr "No estás autorizado a modificar esta imagen"

#: geovisio/web/items.py:1185
#, python-format
msgid "Picture %(p)s is in %(s)s state, its visibility can't be changed for now"
msgstr ""
"La imagen %(p)s está en estado %(s)s, su visibilidad no puede modificarse "
"por ahora"

#: geovisio/web/map.py:124
msgid "One of required parameter is empty"
msgstr "Está vacío uno de los parámetros obligatorios"

#: geovisio/web/map.py:126
msgid "Tile format is invalid, should be either pbf or mvt"
msgstr "El formato de mosaico de teselas no es válido, debe ser pbf o mvt"

#: geovisio/web/map.py:130 geovisio/web/map.py:132
msgid "X or Y parameter is out of bounds"
msgstr "X o Y están fuera de rango"

#: geovisio/web/map.py:134
msgid "Z parameter is out of bounds (should be 0-15)"
msgstr "El parámetro Z está fuera de rango (debe estar entre 0 y 15)"

#: geovisio/web/map.py:145
msgid "Impossible to get tile"
msgstr "Imposible recuperar la tesela"

#: geovisio/web/params.py:101
msgid "Parameter datetime should contain one or two dates"
msgstr "El parámetro datetime debe contener una o dos fechas"

#: geovisio/web/params.py:171
msgid ""
"Parameter bbox must contain valid longitude (-180 to 180) and latitude "
"(-90 to 90) values"
msgstr ""
"El parámetro bbox debe contener valores válidos de longitud (entre -180 y "
"180) y latitud (entre -90 y 90)"

#: geovisio/web/params.py:176
msgid "Parameter bbox must be in format [minX, minY, maxX, maxY]"
msgstr "El parámetro bbox debe seguir el formato [mínX, mínY, máxX, máxY]"

#: geovisio/web/params.py:213
#, python-format
msgid "Parameter %(p)s must be coordinates in lat,lon format"
msgstr "El parámetro %(p)s debe seguir el formato de coordenadas lat,lon"

#: geovisio/web/params.py:216
#, python-format
msgid "Longitude in parameter %(p)s is not valid (should be between -180 and 180)"
msgstr ""
"La longitud en el parámetro %(p)s no es válida (debe estar entre -180 y 180)"

#: geovisio/web/params.py:217
#, python-format
msgid "Latitude in parameter %(p)s is not valid (should be between -90 and 90)"
msgstr ""
"La latitud en el parámetro %(p)s no es válida (debe estar entre -90 y 90)"

#: geovisio/web/params.py:240 geovisio/web/params.py:253
#, python-format
msgid ""
"Parameter %(p)s is invalid (should be a distance range in meters like "
"\"5-15\")"
msgstr ""
"El parámetro %(p)s no es válido (debería ser un rango de distancias en "
"metros, como «5-15»)"

#: geovisio/web/params.py:246
#, python-format
msgid "Parameter %(p)s has a min value greater than its max value"
msgstr "El parámetro %(p)s tiene un valor mínimo más grande que su valor máximo"

#: geovisio/web/params.py:320
#, python-format
msgid "Parameter %(p)s must be a valid list"
msgstr "El parámetro %(p)s debe ser una lista válida"

#: geovisio/web/params.py:444
msgid "Unsupported sortby parameter: invalid column name"
msgstr "Nombre de columna inválido para el parámetro sortby"

#: geovisio/web/params.py:452
msgid "Unsupported sortby parameter: syntax isn't correct"
msgstr "Parámetro sortby inválido: la sintaxis no es correcta"

#: geovisio/web/params.py:478
#, python-format
msgid "limit parameter should be a valid, positive integer (between 1 and %(v)s)"
msgstr ""
"El parámetro limit debe ser un número entero y positivo (entre 1 y %(v)s)"

#: geovisio/web/params.py:481
#, python-format
msgid "limit parameter should be an integer between 1 and %(v)s"
msgstr "El parámetro limit debe ser un número entero entre 1 y %(v)s"

#: geovisio/web/params.py:492
msgid "longitude needs to be between -180 and 180"
msgstr "La longitud ha de estar entre -180 y 180"

#: geovisio/web/params.py:502
msgid "latitude needs to be between -90 and 90"
msgstr "La latitud ha de estar entre -90 y 90"

#: geovisio/web/pictures.py:205
msgid "Tiles are not available for flat pictures"
msgstr "No hay teselas para las imágenes planas"

#: geovisio/web/pictures.py:210
msgid "Column parameter is invalid, should be an integer"
msgstr "El parámetro de columna no es válido, debe ser un número entero"

#: geovisio/web/pictures.py:213
msgid "Column parameter is invalid"
msgstr "El parámetro de columna no es válido"

#: geovisio/web/pictures.py:218
msgid "Row parameter is invalid, should be an integer"
msgstr "El parámetro de fila no es válido, debe ser un número entero"

#: geovisio/web/pictures.py:221
msgid "Row parameter is invalid"
msgstr "El parámetro de fila no es válido"

#: geovisio/web/rss.py:22
#, python-format
msgid "Sequence \"%(name)s\" by \"%(user)s\" was captured on %(date)s."
msgstr ""
"La secuencia «%(name)s» del usuario «%(user)s» fue tomada en fecha de "
"%(date)s."

#: geovisio/web/rss.py:49
msgid "GeoVisio collections"
msgstr "Colecciones GeoVisio"

#: geovisio/web/rss.py:51
msgid "List of collections from this GeoVisio server"
msgstr "Lista de colecciones de este servidor GeoVisio"

#: geovisio/web/tokens.py:101 geovisio/web/tokens.py:144
#: geovisio/web/tokens.py:232
msgid "Impossible to find token"
msgstr "Token no encontrado"

#: geovisio/web/tokens.py:182
msgid "Impossible to generate a new token"
msgstr "No se puede generar un token nuevo"

#: geovisio/web/tokens.py:237
msgid "Token already claimed by another account"
msgstr "El token ha sido reclamado por otra cuenta"

#: geovisio/web/upload_set.py:173
msgid "Impossible to create an UploadSet"
msgstr "No se puede crear un UploadSet"

#: geovisio/web/upload_set.py:175
msgid "Parameter for creating an UploadSet should be a valid JSON"
msgstr ""
"Los parámetros para crear un UploadSet han de estar en formato JSON válido"

#: geovisio/web/upload_set.py:221 geovisio/web/upload_set.py:719
msgid "UploadSet doesn't exist"
msgstr "El UploadSet no existe"

#: geovisio/web/upload_set.py:269 geovisio/web/upload_set.py:370
msgid "Impossible to parse parameters"
msgstr "No se pueden leer los parámetros"

#: geovisio/web/upload_set.py:307
msgid ""
"Parameter `override_capture_time` is not a valid datetime, it should be "
"an iso formated datetime (like '2017-07-21T17:32:28Z')."
msgstr ""
"El parámetro `override_capture_time` no es una combinación válida de fecha y "
"hora, debe estar en formato ISO 8601 (por ejemplo, '2017-07-21T17:32:28Z')."

#: geovisio/web/upload_set.py:359
msgid "No file was sent"
msgstr "No se envió ningún fichero"

#: geovisio/web/upload_set.py:456 geovisio/web/upload_set.py:702
#, python-format
msgid "UploadSet %(u)s does not exist"
msgstr "El UploadSet %(u)s no existe"

#: geovisio/web/upload_set.py:460
msgid "You're not authorized to add picture to this upload set"
msgstr "No tienes autorización para añadir imágenes a este UploadSet"

#: geovisio/web/upload_set.py:464
msgid "The upload set is already completed, files cannot be pushed to it"
msgstr ""

#: geovisio/web/upload_set.py:491
msgid "The item has already been added to this upload set"
msgstr "Este elemento ya había sido añadido a este UploadSet"

#: geovisio/web/upload_set.py:497
msgid "The same picture has already been sent in a past upload"
msgstr "Ya se había subido la misma imagen en una subida anterior"

#: geovisio/web/upload_set.py:575
msgid "UploadSet doesn't exists"
msgstr ""

#: geovisio/web/upload_set.py:706
msgid "You're not authorized to complete this upload set"
msgstr "No tienes autorización para completar este UploadSet"

#: geovisio/web/upload_set.py:711
msgid ""
"The upload set is already completed, cannot complete it several times for"
" the moment"
msgstr ""

#: geovisio/web/users.py:82
msgid "Impossible to find user"
msgstr "No se encuentra el usuario"

#: geovisio/web/users.py:158
msgid ""
"No search parameter given, you should provide `q=<pattern>` as query "
"parameter"
msgstr ""
"No se proporcionó ningún parámetro de búsqueda, debes incluir el parámetro `"
"q=<patrón de búsqueda>` en la peetición"

#: geovisio/web/utils.py:51
msgid "No default account defined, please contact your instance administrator"
msgstr ""
"No se ha definido cuenta por defecto, por favor ponte en contacto con el "
"administrador de la instancia"

#: geovisio/utils/excluded_areas.py:82
msgid "Impossible to find excluded area"
msgstr "No se encuentra el área de exclusión"

#: geovisio/utils/upload_set.py:158
msgid ""
"The picture is too similar to another one (nearby and taken almost at the "
"same time)"
msgstr ""
"La imagen es demasiado similar a otra (cercana y tomada casi en el mismo "
"instante)"

#: geovisio/utils/upload_set.py:164
msgid ""
"The picture has invalid EXIF or XMP metadata, making it impossible to use"
msgstr "El fichero contiene metadatos EXIF o XMP inválidos, que impiden su uso"

#: geovisio/web/excluded_areas.py:134
msgid "You must be logged-in as admin to access all excluded areas"
msgstr ""
"Has de autenticarte como administrador para acceder a todas las áreas de "
"exclusión"

#: geovisio/web/excluded_areas.py:173 geovisio/web/excluded_areas.py:183
#: geovisio/web/excluded_areas.py:337 geovisio/web/excluded_areas.py:344
msgid "Impossible to create an Excluded Area"
msgstr "No se puede crear un Área de Exclusión"

#: geovisio/web/excluded_areas.py:175 geovisio/web/excluded_areas.py:339
msgid "Parameter for creating an Excluded Area should be a valid JSON"
msgstr ""
"Los parámetros de creación de un Área de Exclusión deben estar en formato "
"JSON válido"

#: geovisio/web/excluded_areas.py:178 geovisio/web/excluded_areas.py:236
msgid "You must be logged-in as admin to edit excluded areas"
msgstr ""
"Has de autenticarte como administrador para modificar áreas de exclusión"

#: geovisio/web/excluded_areas.py:273
msgid "You must be logged-in as admin to delete excluded areas"
msgstr "Has de autenticarte como administrador para borrar áreas de exclusión"

#: geovisio/utils/upload_set.py:161
msgid "The sent file is not a valid JPEG"
msgstr "El fichero enviado no es un fichero JPEG válido"

#: geovisio/web/reports.py:352
msgid "You're not authorized to list reports"
msgstr "No tienes autorización para listar las denuncias"

#: geovisio/web/upload_set.py:216
msgid "You're not authorized to list pictures in this upload set"
msgstr "No tienes autorización para listar imágenes de este UploadSet"

#: geovisio/web/excluded_areas.py:233
msgid "Parameter for replacing all Excluded Areas should be a valid JSON"
msgstr ""
"El parámetro para reemplazar todas las Áreas de Exclusión debe estar en "
"formato JSON válido"

#: geovisio/utils/upload_set.py:167
msgid "Something went very wrong, but not due to the picture itself"
msgstr "Algo se rompió de mala manera, pero el problema no viene de la imagen"

#: geovisio/web/excluded_areas.py:231 geovisio/web/excluded_areas.py:243
msgid "Impossible to replace all Excluded Areas"
msgstr "No se pueden reemplazar todas las Áreas de Exclusión"

#: geovisio/web/items.py:1048
#, python-format
msgid "Collection %(s)s wasn't found in database"
msgstr "La colección %(s)s no se encuentra en la base de datos"

#: geovisio/web/items.py:1052
msgid "You're not authorized to add picture to this collection"
msgstr "No estás autorizado a añadir imágenes a esta colección"

#: geovisio/web/items.py:1057
msgid "The collection has been deleted, impossible to add pictures to it"
msgstr "La colección ha sido borrada, no se le pueden añadir imágenes"

#: geovisio/web/items.py:1091 geovisio/web/upload_set.py:622
msgid "Picture has invalid metadata"
msgstr "La imagen tiene metadatos inválidos"

#: geovisio/web/reports.py:89 geovisio/web/reports.py:99
msgid "Impossible to create a Report"
msgstr "No se puede crear una denuncia"

#: geovisio/web/reports.py:91
msgid "Parameter for creating a Report should be a valid JSON"
msgstr ""
"Los parámetros para crear una denuncia deben estar en formato JSON válido"

#: geovisio/web/reports.py:144
msgid "Only authenticated users can access reports"
msgstr "Solo pueden acceder a las denuncias los usuarios autenticados"

#: geovisio/web/reports.py:148 geovisio/web/reports.py:266
msgid "Report doesn't exist"
msgstr "La denuncia no existe"

#: geovisio/web/reports.py:157
msgid "You're not authorized to access this report"
msgstr "No estás autorizado para acceder a esta denuncia"

#: geovisio/web/excluded_areas.py:136
msgid "You're not authorized to access all excluded areas"
msgstr "No tienes autorización para acceder a todas las áreas de exclusión"

#: geovisio/web/reports.py:277
msgid "You're not authorized to edit this Report"
msgstr "No estás autorizado para editar esta denuncia"

#: geovisio/web/reports.py:284
msgid "Impossible to edit the Report"
msgstr "No se puede editar la denuncia"

#: geovisio/web/reports.py:286
msgid "Parameter for editing the Report should be a valid JSON"
msgstr "El parámetro para editar la denuncia debe estar en formato JSON válido"

#: geovisio/web/upload_set.py:630
msgid ""
"Impossible to open file as image. The only supported image format is jpg."
msgstr ""
"Imposible abrir el fichero en tanto que imagen. El único formato admitido es "
"jpg."

#: geovisio/web/upload_set.py:763
msgid "You're not authorized to delete this upload set"
msgstr "No tienes autorización para borrar este UploadSet"
